### ISSUE TITLE
Snowflake company problems are not loading

### ISSUE THREAD

**Issue by jovin-nicholas** [31b4/Leetcode-Premium-Bypass#47]
Snowflake company problems are not loading

**To Reproduce**
1. Go to https://leetcode.com/problemset/
2. Scroll down to Trending Companies
3. Search and Click on Snowflake
4. See loading screen

**Expected behavior**
Get a list of problems similar to other companies problem list

**Screenshots**
<img width="1458" alt="Screenshot 2024-01-18 at 3 58 10 PM" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/32580407/ad16b5b8-07c4-43b0-b1f5-831b1d21c7fe">

**Desktop (please complete the following information):**

**Comment by 31b4** [comment]
@jovin-nicholas thanks for letting me know, i will update them in 24 hours!

**Comment by 31b4** [comment]
@jovin-nicholas sorry i cant fix this in 24hours, it's a bit complicated, im gonna have to make a new leetcode scalper, to refresh the whole database, because sadly the current is outdated.
Until then here is a screenshot of it.
<img width="913" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/e77753d5-7ebf-4cc2-be5b-8864d309b66f">
