### ISSUE TITLE
Not able to click on any premium features The website is not responding

### ISSUE THREAD

**Issue by harry-nyx** [31b4/Leetcode-Premium-Bypass#55]
**Describe the bug**
I have installed the extension and the premium features seem to be unlocked but when i click on them they don't respond 
<img width="960" alt="Screenshot 2024-01-20 090301" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/157190867/9e267563-0ff5-4854-9da2-9c9446d444d6">

**Comment by 31b4** [comment]
Okay, this is interesting. Does the extension has permissions enabled?

**Comment by harry-nyx** [comment]
Yes all permission was enabled

**Comment by Gourav-21** [comment]
hey @harry-nyx, as i can see clearly the extension is working that why's those buttons are green just try refreshing the page

but if it is still not working then something must be overwriting buttons,so the problem is in your browser 

- check if you have any other leetcode extensions and try to disable it 

- if that doesnt work just try to refresh the extension and the webpage 

![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/107918791/b086e0fb-6256-4120-831e-43e9d1118e7b)

- and then if you still dont see this, tell us and try to give a screen recording or just use a different browser

![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/107918791/5232c83e-56a8-4d8e-9c51-3b0e12ce8a92)
